apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: echoheaders
    test: razee
    razee/watch-resource: detail
  name: echoheaders
spec:
  replicas: 5
  selector:
    matchLabels:
      run: echoheaders
  template:
    metadata:
      labels:
        run: echoheaders
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.4
        name: echoheaders
        ports:
        - containerPort: 8080
          protocol: TCP
